//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int Id { get; set; }
        public Nullable<int> Duree { get; set; }
        public string Ville_depart { get; set; }
        public string Ville_arrivee { get; set; }
        public string Date_depart { get; set; }
        public string Date_arrivee { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
        public Nullable<System.DateTime> DateDeMise { get; set; }
        public Nullable<int> id_bus { get; set; }
        public Nullable<System.DateTime> DateDeModification { get; set; }
        public string isvalide { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
