//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autocar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NavetteEntities : DbContext
    {
        public NavetteEntities()
            : base("name=NavetteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonnement> Abonnements { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<SocieteT> SocieteTs { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
